import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('mockups/operations-hub/rule-workspace.js','utf8');
assert.match(source,/function tagNameFromFilename\(fileName\)/);
assert.match(source,/\^\(\.\+\)_일괄적용\\\.\(xlsx\|xls\|csv\)\$/i);
assert.match(source,/mode:'filename_tag'/);
assert.match(source,/A열만 SKU로 읽고 B열 이후는 메모용으로 무시/);
assert.match(source,/const rows=await fileRows\(file,\{tagImport:true\}\)/);
assert.match(source,/previewTagImport\(rows,\{fileName:file\.name\}\)/);
assert.match(source,/data\?\.mode==='filename_tag'\?data\.resolvedTagId/);
assert.match(source,/sheetRows:TAG_IMPORT_MAX_ROWS\+2/);
assert.match(source,/range=\{s:\{r:0,c:0\},e:\{r:endRow,c:1\}\}/);
console.log('PASS filename tag import: <태그명>_일괄적용 file mode uses A only and reuses common tag RPC path.');
