import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync(new URL("../supabase/migrations/20260818033238_operations_hub_multilink_bom.sql", import.meta.url), "utf8");
const html = fs.readFileSync(new URL("../mockups/operations-hub/index.html", import.meta.url), "utf8");
const data = fs.readFileSync(new URL("../mockups/operations-hub/data-service.js", import.meta.url), "utf8");
const app = fs.readFileSync(new URL("../mockups/operations-hub/app.js", import.meta.url), "utf8");
const ambiguityFix = fs.readFileSync(new URL("../supabase/migrations/20260818034744_exclude_ambiguous_legacy_listing_options.sql", import.meta.url), "utf8");
const upsertFix = fs.readFileSync(new URL("../supabase/migrations/20260818034857_fix_multilink_component_upsert_conflict.sql", import.meta.url), "utf8");
const partialRefreshFix = fs.readFileSync(new URL("../supabase/migrations/20260818035322_global_identity_check_for_partial_link_refresh.sql", import.meta.url), "utf8");
const inventoryDraftMigration = fs.readFileSync(new URL("../supabase/migrations/20260818045443_operations_hub_bundle_inventory_drafts.sql", import.meta.url), "utf8");
const disconnectMigration = fs.readFileSync(new URL("../supabase/migrations/20260821200000_disconnect_legacy_listing_component.sql", import.meta.url), "utf8");
const pageFirstGraphMigration = fs.readFileSync(new URL("../supabase/migrations/20260823082547_optimize_operations_hub_listing_graph_page_first.sql", import.meta.url), "utf8");
const exactGraphMigration = fs.readFileSync(new URL("../supabase/migrations/20260825054226_operations_hub_exact_listing_graph.sql", import.meta.url), "utf8");

assert.match(migration, /operations_hub_seller_listings[\s\S]*operations_hub_listing_components[\s\S]*component_qty integer[\s\S]*check \(component_qty > 0\)/, "bundle graph must have durable listing and positive-quantity component records");
assert.match(migration, /operations_hub_listing_component_projection[\s\S]*explicit_components[\s\S]*legacy_components/, "explicit graph must retain current 1:1 mappings through a compatibility projection");
assert.match(migration, /legacy_promoted[\s\S]*Preserve the current 1:1 mapping/, "promoting a listing must preserve its existing SKU before adding bundle components");
assert.match(migration, /min\(floor\(projection\.sellpia_available_stock::numeric \/ projection\.component_qty\)\)/, "bundle stock must be the limiting component stock divided by required quantity");
assert.match(migration, /enable row level security[\s\S]*security_invoker = true[\s\S]*grant execute/i, "public graph access must keep RLS, invoker views, and explicit grants");
assert.match(html, /data-page="multi-links"[\s\S]*id="multi-links"[\s\S]*id="multi-link-form"/, "operations hub must expose a dedicated multi-link workspace and editor");
assert.match(data, /attachLinkBadges[\s\S]*loadListingGraph[\s\S]*saveListingComponent[\s\S]*deactivateListingComponent/, "frontend data adapter must expose graph reads, matrix badges, save, and soft-deactivation");
assert.match(app, /matrix-relation-badge[\s\S]*openMultiLinkWorkspace[\s\S]*renderMultiLinkEditor/, "matrix badges must route into the dedicated listing editor");
assert.doesNotMatch(migration, /delete from public\.operations_hub_listing_components/i, "component removal must be an auditable soft-deactivation");
assert.match(ambiguityFix, /edge\.option_code <> ''[\s\S]*identity\.edge_count = 1/, "blank option codes shared by multiple SKUs must not be misclassified as bundles");
assert.match(upsertFix, /on conflict on constraint operations_hub_listing_componen_listing_id_sellpia_sku_code_key/, "component upsert must avoid PL\/pgSQL output-column ambiguity with the actual truncated constraint name");
assert.match(partialRefreshFix, /edge\.sellpia_sku_code = any\(p_skus\)[\s\S]*identity\.edge_count = 1/, "partial cache refresh must validate blank-option identity against the global edge set");
assert.match(inventoryDraftMigration, /stage_operations_hub_listing_inventory_draft[\s\S]*listing\.listing_id[\s\S]*min\(floor\(matrix\.sellpia_available_stock::numeric \/ component\.component_qty\)\)[\s\S]*component\.is_active/, "bundle inventory drafts must recalculate only explicit active components inside the database");
assert.match(inventoryDraftMigration, /v_listing_id is null[\s\S]*먼저 판매처 옵션의 구성을 저장/, "inferred legacy relationships must not create inventory drafts until explicitly confirmed");
assert.match(inventoryDraftMigration, /seller_product_code = v_product_code[\s\S]*seller_option_code[\s\S]*조합 계산재고/, "bundle drafts must target the exact seller listing and enter the existing review queue");
assert.doesNotMatch(inventoryDraftMigration, /security definer/i, "bundle inventory staging must not bypass RLS");
assert.match(html, /multi-link-inventory-action[\s\S]*multi-link-open-queue[\s\S]*multi-link-stage-stock/, "the listing editor must show a reviewable inventory-draft action and queue entry point");
assert.match(data, /stageListingInventoryDraft[\s\S]*stage_operations_hub_listing_inventory_draft/, "the data adapter must expose bundle inventory draft staging");
assert.match(app, /renderMultiLinkInventoryAction[\s\S]*stageListingInventoryDraft[\s\S]*loadChangeQueue/, "staging bundle stock must refresh the listing, queue, dashboard, and matrix review surfaces");
assert.match(html, /drawer-link-manager[\s\S]*drawer-open-multi-links/, "the product drawer must expose integrated component management without removing the full workspace");
assert.match(app, /loadDrawerListingLinks[\s\S]*data-drawer-component-save[\s\S]*data-drawer-component-remove[\s\S]*data-drawer-stage-stock/, "the integrated drawer must add, edit, remove, and stage listing components");
assert.match(disconnectMigration, /disconnect_operations_hub_legacy_listing_component[\s\S]*upsert_operations_hub_listing_component[\s\S]*deactivate_operations_hub_listing_component/, "legacy disconnect must promote and soft-deactivate the inferred edge atomically");
assert.match(disconnectMigration, /v_legacy_count <= 1[\s\S]*마지막 연결/, "legacy disconnect must not remove the last remaining SKU edge");
assert.match(data, /removeListingComponent[\s\S]*disconnect_operations_hub_legacy_listing_component/, "the data adapter must route inferred legacy removals through the atomic RPC");
assert.match(app, /data-remove-component[\s\S]*removeListingComponent\(\{componentId:card\.dataset\.componentId \|\| null/, "the multi-link editor must let operators remove inferred as well as explicit components");
assert.match(app, /data-drawer-component-remove[\s\S]*removeListingComponent\(\{componentId:component\.dataset\.componentId \|\| null/, "the product drawer must expose the same inferred-component removal action");
assert.match(html, /id="listing-link-modal"[\s\S]*id="listing-link-components"[\s\S]*id="listing-link-add-toggle"[\s\S]*\+ SKU 추가 연결/, "matrix code clicks must expose a focused listing link manager with current components and an add action");
assert.match(data, /loadListingConnection[\s\S]*get_operations_hub_listing_graph/, "the data adapter must expose a focused exact-listing read");
assert.match(app, /loadListingLinkManager[\s\S]*loadListingConnection[\s\S]*openListingLinkManager/, "the focused manager must use the exact seller listing read before it is opened from a matrix code cell");
assert.match(exactGraphMigration, /get_operations_hub_listing_graph[\s\S]*explicit_listing as materialized[\s\S]*operations_hub_listing_legacy_cache[\s\S]*to_jsonb\(exact_graph\)/, "focused link management must filter one exact listing before component enrichment");
assert.doesNotMatch(exactGraphMigration, /sku_listing_counts|listing_spread|classified as materialized/, "the exact listing read must not run the catalog-wide relation classifier");
assert.match(exactGraphMigration, /security invoker[\s\S]*revoke all[\s\S]*grant execute/i, "the exact listing RPC must preserve invoker permissions");
assert.match(app, /data-link-manager-remove[\s\S]*removeListingComponent/, "the focused manager must disconnect a selected component row");
assert.match(app, /listing-link-add-form[\s\S]*saveListingComponent/, "the focused manager must add another SKU to the selected seller listing");
assert.doesNotMatch(pageFirstGraphMigration, /from public\.operations_hub_listing_graph_live/i, "listing pagination must not materialize the fully enriched compatibility graph");
assert.match(pageFirstGraphMigration, /identity_edges as materialized[\s\S]*classified as materialized[\s\S]*filtered as materialized[\s\S]*paged_keys as materialized[\s\S]*paged_components as materialized/, "listing identities must be classified and paged before component enrichment");
assert.match(pageFirstGraphMigration, /paged_components as materialized[\s\S]*left join public\.operations_hub_sellpia_component_live/, "Sellpia stock enrichment must be scoped to the selected page");
assert.match(pageFirstGraphMigration, /component_metadata_matches[\s\S]*sellpia_own_code[\s\S]*sellpia_product_name[\s\S]*sellpia_option_name/, "page-first reads must retain component metadata search behavior");
assert.match(pageFirstGraphMigration, /'rows'[\s\S]*'count'[\s\S]*'page'[\s\S]*'pageSize'/, "the optimized RPC must preserve its response contract");
assert.match(pageFirstGraphMigration, /security invoker[\s\S]*revoke all[\s\S]*grant execute/i, "the optimized RPC must preserve its permission contract");

console.log("Operations hub multi-link and bundle graph contract: passed");
