import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';
test('tag scope uses all authoritative assignments without textarea; shared selector, bounded recompute and download revalidation',async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});try{const p=await browser.newPage();p.setDefaultTimeout(10000);await p.setContent('<select id="export-scope-mode"><option value="all">all</option><option value="tag">tag</option></select><select id="export-scope-tag"><option value="T">2.2</option></select><div id="export-workflow-v2"><div class="export-channel-grid"></div></div>');await p.addStyleTag({path:'mockups/operations-hub/sellpia-patch-export.css'});await p.addScriptTag({path:process.env.XLSX_BROWSER_SCRIPT});await p.addScriptTag({path:'mockups/operations-hub/sellpia-patch-export.js'});
 await p.evaluate(()=>{window.codes=Array.from({length:2690},(_,i)=>'SKU-'+i);window.memberReads=0;window.exports=[];window.recalculations=[];window.SystemV3Data={loadTagCatalog:async()=>({rows:[{tag_id:'T',tag_name:'14K_실입고가_2.2배율',option_count:2690}]}),loadTagMembers:async a=>{memberReads++;return {rows:codes.slice((a.page-1)*1000,a.page*1000).map(s=>({sellpia_sku_code:s})),count:codes.length};},loadSellpiaPatchRows:async a=>a.skus.map(s=>({sellpia_sku_code:s,sellpia_source_stock:3,system_stock:4}))};window.HubPriceMaterializer={materialize:async a=>{recalculations.push(a);return {generationId:1,completedSkus:a.skus.length,errorRows:0};}};XLSX.writeFile=(book)=>exports.push(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1}));SellpiaPatchExport.mount();});
 await p.locator('#export-scope-mode').selectOption('tag');await p.waitForFunction(()=>document.querySelector('#sellpia-patch-tag').options.length===2);await p.locator('#export-scope-tag').selectOption('T');await p.waitForFunction(()=>document.querySelector('#sellpia-patch-tag').value==='T');assert.equal(await p.locator('#sellpia-patch-skus').isVisible(),false);await p.locator('[data-patch-field=base]').uncheck();await p.locator('[data-patch-field=stock]').check();await p.locator('#sellpia-patch-preview-run').click();await p.waitForFunction(()=>document.querySelector('#sellpia-patch-status').textContent.includes('2690 SKU'));assert.equal(await p.locator('#sellpia-patch-skus').inputValue(),'');assert.equal(await p.evaluate(()=>memberReads),3);await p.locator('#sellpia-patch-download').click();await p.waitForFunction(()=>exports.length===1);assert.equal(await p.evaluate(()=>exports[0].length),2691);assert.deepEqual(await p.evaluate(()=>exports[0][0]),['Sellpia SKU','재고']);assert.equal(await p.evaluate(()=>memberReads),6);
 await p.locator('#sellpia-patch-recalculate').click();await p.waitForFunction(()=>recalculations.length===1);assert.equal(await p.evaluate(()=>recalculations[0].boundedSkus.length),2690);assert.deepEqual(await p.evaluate(()=>recalculations[0].sources),[]);
 await p.locator('#sellpia-patch-preview-run').click();await p.waitForFunction(()=>!document.querySelector('#sellpia-patch-download').disabled);await p.evaluate(()=>codes[2689]='CHANGED-1');await p.locator('#sellpia-patch-download').click();await p.waitForFunction(()=>document.querySelector('#sellpia-patch-status').textContent.includes('assignment가 변경'));assert.equal(await p.evaluate(()=>exports.length),1);assert.equal(await p.locator('#sellpia-patch-download').isDisabled(),true);
 }finally{await browser.close();}
});
