import assert from 'node:assert/strict';
await import('../mockups/operations-hub/tag-price-workspace.js');
const {calculate}=globalThis.TagPriceModel;
const profile=id=>({sku_tags:[{tag_id:id}],product_tags:[]});
const products={'six':{sellpia_source_purchase_price:10000,__profile:profile(1)},'eight':{__profile:profile(2)}};
const formulas={1:{enabled:true,basis:'purchase',multiplier:1.5,add:0,unit:100,rounding:'nearest'},2:{enabled:true,basis:'sku',multiplier:1,add:2000,unit:100,rounding:'nearest'}};
assert.equal(calculate('six',products,formulas,{}).value,15000);
assert.equal(calculate('eight',products,formulas,{eight:'six'}).value,17000);
formulas[2].multiplier=1.2;formulas[2].add=0;
assert.equal(calculate('eight',products,formulas,{eight:'six'}).value,18000);
assert.throws(()=>calculate('eight',products,formulas,{}),/미지정/);
assert.throws(()=>calculate('eight',products,formulas,{eight:'eight'}),/순환/);
products.six.sellpia_source_purchase_price=null;
assert.throws(()=>calculate('eight',products,formulas,{eight:'six'}),/기준가격 없음/);
products.six.sellpia_source_purchase_price=0;
assert.equal(calculate('six',products,formulas,{}).value,0);
products.six.__profile.sku_tags.push({tag_id:2});
assert.throws(()=>calculate('six',products,formulas,{}),/2개/);
console.log('PASS chained 6mm/8mm add and multiply, zero, missing basis, conflicting tags, cycle');
